### ISSUE TITLE
Missing authorship for GSoC students

### ISSUE THREAD

**Issue by matteobachetti** [StingraySoftware/stingraypaper#13]
@orkohunter
@usmanwardag
@haroonrashid235
@omargamal8
You have worked for Stingray as part of GSoC. As such, you are invited to co-author the Stingray paper!
If you agree, please send us your complete names and affiliation(s) :)

**Comment by usmanwardag** [comment]
Sure! 
Full Name: Usman Mahmood Khan
Affiliation: Department of Computer Science, North Carolina State University, Raleigh, USA

**Comment by haroonrashid235** [comment]
Full Name: Haroon Rashid
Affiliation: National University of Sciences and Technology, Islamabad.

**Comment by OrkoHunter** [comment]
Thank you @matteobachetti ! :)

Himanshu Mishra
IIT Kharagpur, India

**Comment by omargamal8** [comment]
Thank you for the invitation.
Name: Omar Hammad
Affiliation: AinShams University, Egypt

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dhuppenkothen** [comment]
Thanks all for your quick responses! You have all been added to the paper. :)
