### ISSUE TITLE
[referee report] Add warning about fitting sinc^2 function

### ISSUE THREAD

**Issue by dhuppenkothen** [StingraySoftware/stingraypaper#22]
"Page 12, col 1: You state that "stingray has functionality to fit these periodograms with a sinc^2 function or alternatively a Gaussian model, and find the mean frequency with high precision." Fitting a Gaussian to a periodogram will give the mean frequency, but I think this statement should be followed with an explicit warning that, as the data points in a periodogram are not independent, fitting should be done with caution and the width on this Gaussian is not the error on this measurement (see Section 7 of VanderPlas 2018)"

cc @matteobachetti: This looks like part of the pulsar stuff, I think? So I'm handing this over to you. :)

**Comment by dhuppenkothen** [comment]
@matteobachetti This was solved in #24, right?

**Comment by matteobachetti** [comment]
Yes!
